-- Create docentes table
CREATE TABLE IF NOT EXISTS `docentes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `matricula` varchar(50) NOT NULL,
  `nome` varchar(100) NOT NULL,
  `rg` varchar(50) DEFAULT NULL,
  `orgao_expedidor` varchar(50) DEFAULT NULL,
  `cpf` varchar(14) NOT NULL,
  `lattes` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `fone_residencial` varchar(20) DEFAULT NULL,
  `fone_profissional` varchar(20) DEFAULT NULL,
  `fone_celular` varchar(20) DEFAULT NULL,
  `instituicao` varchar(100) DEFAULT NULL,
  `data_ingresso` date DEFAULT NULL,
  `cargo` varchar(100) DEFAULT NULL,
  `lotacao` varchar(100) DEFAULT NULL,
  `cidade_lotacao` varchar(100) DEFAULT NULL,
  `disciplinas_instrutor` text DEFAULT NULL,
  `disciplinas_conteudista` text DEFAULT NULL,
  `formacao_tecnologica_1` varchar(100) DEFAULT NULL,
  `formacao_tecnologica_2` varchar(100) DEFAULT NULL,
  `graduacao_1` varchar(100) DEFAULT NULL,
  `graduacao_2` varchar(100) DEFAULT NULL,
  `graduacao_3` varchar(100) DEFAULT NULL,
  `especializacao_gestao` varchar(100) DEFAULT NULL,
  `especializacao_outros` varchar(100) DEFAULT NULL,
  `mestrado` varchar(100) DEFAULT NULL,
  `doutorado` varchar(100) DEFAULT NULL,
  `pos_doutorado` varchar(100) DEFAULT NULL,
  `situacao` varchar(50) DEFAULT '1º Cadastro',
  PRIMARY KEY (`id`),
  UNIQUE KEY `cpf` (`cpf`),
  UNIQUE KEY `matricula` (`matricula`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;